/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Log Event
 #	author : miyako
 #	2016/02/11
 #
 # --------------------------------------------------------------------------------*/



// --- Log
void LOG_WRITE_ENTRY(sLONG_PTR *pResult, PackagePtr pParams);
void LOG_REGISTER_SOURCE(sLONG_PTR *pResult, PackagePtr pParams);
void LOG_SET_SOURCE(sLONG_PTR *pResult, PackagePtr pParams);
void LOG_GET_SOURCE(sLONG_PTR *pResult, PackagePtr pParams);
